# Generated by Django 4.0.4 on 2022-06-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=32)),
                ('item_id', models.IntegerField()),
                ('description', models.CharField(max_length=64)),
                ('fbx', models.CharField(max_length=64)),
                ('ue_reference', models.CharField(max_length=64)),
            ],
        ),
    ]
